//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model.ModelView
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MenusView
    {
        public int m_id { get; set; }
        public int m_parent_mid { get; set; }
        public string m_name { get; set; }
        public string m_url { get; set; }
        public int m_sortid { get; set; }
        public int m_status { get; set; }
        public string m_picname { get; set; }
        public int m_level { get; set; }
        public string m_remark { get; set; }
        public string m_exp1 { get; set; }
        public Nullable<int> m_exp2 { get; set; }
        public System.DateTime m_add_time { get; set; }
    }
}
