//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model.ModelView
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserInfoView
    {
    
    
        public int user_id { get; set; }
        public string u_name { get; set; }
        public string u_pwd { get; set; }
        public string real_name { get; set; }
        public string u_telephone { get; set; }
        public string u_email { get; set; }
        public int u_is_lock { get; set; }
        public System.DateTime u_add_time { get; set; }
    
        public virtual ICollection<ContentsView> Contents { get; set; }
        public virtual ICollection<NewsView> News { get; set; }
    }
}
