//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model.ModelView
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class feedbackView
    {
        [DisplayName("编号")]
        public int f_id { get; set; }
        [DisplayName("留言标题")]
        [Required(ErrorMessage = "留言标题不能为空")]
        public string f_title { get; set; }
        [DisplayName("留言内容")]
        [Required(ErrorMessage = "留言内容不能为空")]
        public string f_content { get; set; }
        [DisplayName("留言人")]
        [Required(ErrorMessage = "留言人不能为空")]
        public string fuser_name { get; set; }
        [DisplayName("留言人电话")]
        [Required(ErrorMessage = "留言人电话不能为空")]
        public string fuser_tel { get; set; }
        [DisplayName("留言人QQ")]
        public string fuser_qq { get; set; }
        [DisplayName("留言人Email")]
        public string fuser_email { get; set; }
        [DisplayName("留言时间l")]
        public System.DateTime fadd_time { get; set; }
        [DisplayName("回复内容")]
        public string freply_content { get; set; }
        [DisplayName("回复时间")]
        public Nullable<System.DateTime> freply_time { get; set; }
        [DisplayName("是否禁用")]
        public bool is_lock { get; set; }
    }
}
