//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model.ModelView
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductView
    {

        public int p_id { get; set; }
        [DisplayName("产品编号")]
        public string p_photo_no { get; set; }
        [DisplayName("产品名称"), Required(ErrorMessage = "产品名称不能为空")]
        public string p_title { get; set; }
        [DisplayName("所属分类")]
        public int category_id { get; set; }
        public string img_url { get; set; }
        [DisplayName("产品描述")]
        public string p_content { get; set; }
        public int sort_id { get; set; }
        public int click { get; set; }
        public System.DateTime add_time { get; set; }
        public byte is_lock { get; set; }

        public virtual CategoryView Category { get; set; }
    }
}
