//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model.ModelView
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ContentsView
    {
        [DisplayName("编号")]
        public int cnt_id { get; set; }
        [DisplayName("标题"),Required(ErrorMessage="标题不能为空")]
        public string cnt_title { get; set; }
        [DisplayName("所属类别")]
        public int category_id { get; set; }
        [DisplayName("内容"), Required(ErrorMessage = "内容不能为空")]
        public string cnt_content { get; set; }
        [DisplayName("导航url")]
        public string cnt_linkurl { get; set; }        
        public string cnt_imgurl { get; set; }
        public int user_id { get; set; }
        public byte cnt_is_lock { get; set; }
        public System.DateTime cnt_add_time { get; set; }
        public string cnt_exp1 { get; set; }
        public Nullable<int> cnt_exp2 { get; set; }
    
        public virtual CategoryView Category { get; set; }
        public virtual UserInfoView UserInfo { get; set; }
    }
}
