//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model.ModelView
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
     

    public partial class UserInfoView
    {


        public int user_id { get; set; }
        [DisplayName("用户名")]
        [Required(ErrorMessage = "用户名不能为空")]
        [Remote("CheckUname","UserInfo",HttpMethod="get", ErrorMessage="该用户名已经存在")]
        public string u_name { get; set; }
        [DisplayName("密码")]
        [Required(ErrorMessage = "密码不能为空")]
        [DataType(DataType.Password)]
        public string u_pwd { get; set; }
        [DisplayName("确认密码")]
        [System.ComponentModel.DataAnnotations.Compare("u_pwd", ErrorMessage = "确认密码必须与原密码保持一致")]
        [DataType(DataType.Password)]
        public string u_confim_pwd { get; set; }
        [DisplayName("真实名称")]
        [Required()]
        public string real_name { get; set; }
        [DisplayName("电话")]
        [RegularExpression("^13[0-9]{9}|15[012356789][0-9]{8}|18[0256789][0-9]{8}|147[0-9]{8}$", ErrorMessage = "电话的格式不正确")]
        public string u_telephone { get; set; }
        [DisplayName("电邮")]
        [RegularExpression("^\\w+((-\\w+)|(\\.\\w+))*\\@[A-Za-z0-9]+((\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z0-9]+$", ErrorMessage = "电邮的格式不正确")]
        public string u_email { get; set; }
        [DisplayName("是否禁用")]
        public int u_is_lock { get; set; }
        public System.DateTime u_add_time { get; set; }

        [DisplayName("验证码")]
        [Required(ErrorMessage = "验证码不能为空")]
        public string VCode { get; set; }

        public virtual ICollection<ContentsView> Contents { get; set; }
        public virtual ICollection<NewsView> News { get; set; }
    }
}
