//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Contents = new HashSet<Contents>();
            this.News = new HashSet<News>();
            this.Product = new HashSet<Product>();
        }
    
        public int c_id { get; set; }
        public int c_type { get; set; }
        public string c_title { get; set; }
        public int parent_id { get; set; }
    
        public virtual ICollection<Contents> Contents { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
