//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS11.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        public int cnt_id { get; set; }
        public string cnt_title { get; set; }
        public int category_id { get; set; }
        public string cnt_content { get; set; }
        public string cnt_linkurl { get; set; }
        public string cnt_imgurl { get; set; }
        public int user_id { get; set; }
        public byte cnt_is_lock { get; set; }
        public System.DateTime cnt_add_time { get; set; }
        public string cnt_exp1 { get; set; }
        public Nullable<int> cnt_exp2 { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
